# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Sync certificates and provisioning profiles"
  lane :certs do
    match(type: "appstore")
  end

  desc "Build and upload to App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_KEY_FILEPATH"]
    )
    match(type: "appstore", readonly: true, api_key: api_key)
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "X5FF3SWL39",
      code_sign_identity: "Apple Distribution",
      profile_name: "match AppStore com.abassaf.fourhundredscorekeeper",
      bundle_identifier: "com.abassaf.fourhundredscorekeeper",
      path: "ios/400Scorekeeper.xcodeproj"
    )
    increment_build_number(xcodeproj: "ios/400Scorekeeper.xcodeproj")
    build_app(
      workspace: "ios/400Scorekeeper.xcworkspace",
      scheme: "400Scorekeeper",
      configuration: "Release"
    )
    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end
end

platform :android do
  desc "Build and upload to Google Play"
  lane :release do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "android/",
      properties: {
        "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEYSTORE_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"],
      }
    )
    upload_to_play_store(
      track: "internal",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
